export const IS_DEV_ENV = process.env.NODE_ENV === 'development';

const IS_DEV_GITHUB_ENV = process.env.GITHUB_ENV === 'development';

export const IS_STAGE_ENV = IS_DEV_ENV || IS_DEV_GITHUB_ENV;

export const BACKGROUND_IS_WORKER = process.env.BACKGROUND_IS_WORKER === 'true';

export const EnvVars = {
  TEMPLE_WALLET_API_URL: process.env.TEMPLE_WALLET_API_URL!,
  TEMPLE_WALLET_DEXES_API_URL: process.env.TEMPLE_WALLET_DEXES_API_URL!,
  TEMPLE_WALLET_JITSU_TRACKING_HOST: process.env.TEMPLE_WALLET_JITSU_TRACKING_HOST!,
  TEMPLE_WALLET_JITSU_WRITE_KEY: process.env.TEMPLE_WALLET_JITSU_WRITE_KEY!,
  TEMPLE_WALLET_EXOLIX_API_KEY: process.env.TEMPLE_WALLET_EXOLIX_API_KEY!,
  TEMPLE_WALLET_EVERSTAKE_API_KEY: process.env.TEMPLE_WALLET_EVERSTAKE_API_KEY!,
  TEMPLE_WALLET_EVERSTAKE_LINK_ID: process.env.TEMPLE_WALLET_EVERSTAKE_LINK_ID!,
  TEMPLE_WALLET_UTORG_SID: process.env.TEMPLE_WALLET_UTORG_SID!,
  TEMPLE_WALLET_ROUTE3_AUTH_TOKEN: process.env.TEMPLE_WALLET_ROUTE3_AUTH_TOKEN!
} as const;
