import PackageJSON from '../../package.json';

export const APP_VERSION = PackageJSON.version;

// Detects the Mises browser or a Chromium-based browser on iOS (e.g., Chrome on iPhone/iPad, which includes 'CriOS' in userAgent).
// Mises supports desktop extensions on mobile, so it's treated as compatible in this context.
export const IS_MISES_BROWSER =
  // @ts-expect-error
  navigator.userAgentData?.brands?.some(b => b.brand === 'Mises') || navigator.userAgent.includes('CriOS/');

const IS_GOOGLE_CHROME_BROWSER =
  // @ts-expect-error
  navigator.userAgentData?.brands?.some(b => b.brand === 'Google Chrome');

const IS_BRAVE_BROWSER =
  // @ts-expect-error
  navigator.userAgentData?.brands?.some(b => b.brand === 'Brave');

export const IS_SIDE_PANEL_AVAILABLE = IS_GOOGLE_CHROME_BROWSER || IS_BRAVE_BROWSER;

export const IS_CHROMIUM_BROWSER = process.env.TARGET_BROWSER === 'chrome';

export const IS_DEV_ENV = process.env.NODE_ENV === 'development';

export const IS_FIREFOX = process.env.TARGET_BROWSER === 'firefox';

const IS_DEV_GITHUB_ACTION_RUN_ENV = process.env.GITHUB_ACTION_RUN_ENV === 'development';

export const IS_STAGE_ENV = IS_DEV_ENV || IS_DEV_GITHUB_ACTION_RUN_ENV;

export const BACKGROUND_IS_WORKER = process.env.BACKGROUND_IS_WORKER === 'true';

export const EnvVars = {
  TEMPLE_WALLET_API_URL: process.env.TEMPLE_WALLET_API_URL!,
  TEMPLE_WALLET_DEXES_API_URL: process.env.TEMPLE_WALLET_DEXES_API_URL!,
  TEMPLE_ADS_API_URL: process.env.TEMPLE_ADS_API_URL!,
  TEMPLE_WALLET_JITSU_TRACKING_HOST: process.env.TEMPLE_WALLET_JITSU_TRACKING_HOST!,
  TEMPLE_WALLET_JITSU_WRITE_KEY: process.env.TEMPLE_WALLET_JITSU_WRITE_KEY!,
  TEMPLE_WALLET_EXOLIX_API_KEY: process.env.TEMPLE_WALLET_EXOLIX_API_KEY!,
  TEMPLE_WALLET_EVERSTAKE_API_KEY: process.env.TEMPLE_WALLET_EVERSTAKE_API_KEY!,
  TEMPLE_WALLET_EVERSTAKE_LINK_ID: process.env.TEMPLE_WALLET_EVERSTAKE_LINK_ID!,
  TEMPLE_WALLET_UTORG_SID: process.env.TEMPLE_WALLET_UTORG_SID!,
  TEMPLE_WALLET_ROUTE3_AUTH_TOKEN: process.env.TEMPLE_WALLET_ROUTE3_AUTH_TOKEN!,
  TEMPLE_WALLET_MOONPAY_API_KEY: process.env.TEMPLE_WALLET_MOONPAY_API_KEY!,
  TEMPLE_WALLET_KOLIBRIO_PARAMS: process.env.TEMPLE_WALLET_KOLIBRIO_PARAMS!,
  TEMPLE_FIREBASE_CONFIG: process.env.TEMPLE_FIREBASE_CONFIG!,
  TEMPLE_FIREBASE_MESSAGING_VAPID_KEY: process.env.TEMPLE_FIREBASE_MESSAGING_VAPID_KEY!,
  TEMPLE_WALLET_DEVELOPMENT_BRANCH_NAME: process.env.TEMPLE_WALLET_DEVELOPMENT_BRANCH_NAME!,
  HYPELAB_API_URL: process.env.HYPELAB_API_URL!,
  HYPELAB_HIGH_PLACEMENT_SLUG: process.env.HYPELAB_HIGH_PLACEMENT_SLUG!,
  HYPELAB_WIDE_PLACEMENT_SLUG: process.env.HYPELAB_WIDE_PLACEMENT_SLUG!,
  HYPELAB_INTERNAL_NATIVE_PLACEMENT_SLUG: process.env.HYPELAB_INTERNAL_NATIVE_PLACEMENT_SLUG!,
  HYPELAB_PROPERTY_SLUG: process.env.HYPELAB_PROPERTY_SLUG!,
  HYPELAB_EXTERNAL_PROPERTY_SLUG: process.env.HYPELAB_EXTERNAL_PROPERTY_SLUG!,
  HYPELAB_ADS_WINDOW_URL: process.env.HYPELAB_ADS_WINDOW_URL!,
  HYPELAB_INTERNAL_MEDIUM_PLACEMENT_SLUG: process.env.HYPELAB_INTERNAL_MEDIUM_PLACEMENT_SLUG!,
  HYPELAB_EXTERNAL_MEDIUM_PLACEMENT_SLUG: process.env.HYPELAB_EXTERNAL_MEDIUM_PLACEMENT_SLUG!,
  HYPELAB_EXTERNAL_SMALL_PLACEMENT_SLUG: process.env.HYPELAB_EXTERNAL_SMALL_PLACEMENT_SLUG!,
  HYPELAB_EXTERNAL_NATIVE_PLACEMENT_SLUG: process.env.HYPELAB_EXTERNAL_NATIVE_PLACEMENT_SLUG!,
  PERSONA_ADS_API_KEY: process.env.PERSONA_ADS_API_KEY!,
  PERSONA_ADS_ENABLED: process.env.PERSONA_ADS_ENABLED === 'true',
  PERSONA_ADS_MISES_BANNER_UNIT_ID: process.env.PERSONA_ADS_MISES_BANNER_UNIT_ID!,
  PERSONA_ADS_BANNER_UNIT_ID: process.env.PERSONA_ADS_BANNER_UNIT_ID!,
  PERSONA_ADS_MISES_WIDE_BANNER_UNIT_ID: process.env.PERSONA_ADS_MISES_WIDE_BANNER_UNIT_ID!,
  PERSONA_ADS_WIDE_BANNER_UNIT_ID: process.env.PERSONA_ADS_WIDE_BANNER_UNIT_ID!,
  PERSONA_ADS_MISES_MEDIUM_BANNER_UNIT_ID: process.env.PERSONA_ADS_MISES_MEDIUM_BANNER_UNIT_ID!,
  PERSONA_ADS_MEDIUM_BANNER_UNIT_ID: process.env.PERSONA_ADS_MEDIUM_BANNER_UNIT_ID!,
  PERSONA_ADS_MISES_SQUARISH_BANNER_UNIT_ID: process.env.PERSONA_ADS_MISES_SQUARISH_BANNER_UNIT_ID!,
  PERSONA_ADS_SQUARISH_BANNER_UNIT_ID: process.env.PERSONA_ADS_SQUARISH_BANNER_UNIT_ID!,
  TEMPLE_ADS_ORIGIN_PASSPHRASE: process.env.TEMPLE_ADS_ORIGIN_PASSPHRASE!,
  CONVERSION_API_URL: process.env.CONVERSION_API_URL!,
  BITMEDIA_320_50_PLACEMENT_ID: process.env.BITMEDIA_320_50_PLACEMENT_ID!,
  BITMEDIA_320_100_PLACEMENT_ID: process.env.BITMEDIA_320_100_PLACEMENT_ID!,
  BITMEDIA_300_250_PLACEMENT_ID: process.env.BITMEDIA_300_250_PLACEMENT_ID!,
  BITMEDIA_728_90_PLACEMENT_ID: process.env.BITMEDIA_728_90_PLACEMENT_ID!,
  BITMEDIA_300_100_PLACEMENT_ID: process.env.BITMEDIA_300_100_PLACEMENT_ID,
  BITMEDIA_250_250_PLACEMENT_ID: process.env.BITMEDIA_250_250_PLACEMENT_ID,
  BITMEDIA_336_280_PLACEMENT_ID: process.env.BITMEDIA_336_280_PLACEMENT_ID,
  BITMEDIA_160_600_PLACEMENT_ID: process.env.BITMEDIA_160_600_PLACEMENT_ID,
  BITMEDIA_300_600_PLACEMENT_ID: process.env.BITMEDIA_300_600_PLACEMENT_ID,
  BITMEDIA_970_90_PLACEMENT_ID: process.env.BITMEDIA_970_90_PLACEMENT_ID,
  /** Whether ads stubs should be added if loading failed. Set it to `true` only for testing */
  USE_ADS_STUBS: process.env.USE_ADS_STUBS === 'true',
  TAKE_ADS_TOKEN: process.env.TAKE_ADS_TOKEN!,
  GOOGLE_AUTH_PAGE_URL: process.env.GOOGLE_AUTH_PAGE_URL!
} as const;
