export const BLOCK_DURATION = 15_000;

export const METADATA_SYNC_INTERVAL = 4 * BLOCK_DURATION;

export const BALANCES_SYNC_INTERVAL = BLOCK_DURATION;

const LONG_INTERVAL = 5 * 60_000;

export const RATES_SYNC_INTERVAL = LONG_INTERVAL;

export const NOTIFICATIONS_SYNC_INTERVAL = LONG_INTERVAL;

export const USER_ACTION_TIMEOUT = 30_000;

export const CONFIRM_TIMEOUT = LONG_INTERVAL;

export const WALLET_AUTOLOCK_TIME = LONG_INTERVAL;
