export const TEZOS_BLOCK_DURATION = 8_000;

export const EVM_BALANCES_SYNC_INTERVAL = 60_000;

export const ASSETS_SYNC_INTERVAL = 4 * TEZOS_BLOCK_DURATION;

const LONG_INTERVAL = 5 * 60_000;

export const RATES_SYNC_INTERVAL = LONG_INTERVAL;

export const BAKING_STAKE_SYNC_INTERVAL = LONG_INTERVAL;

export const NOTIFICATIONS_SYNC_INTERVAL = LONG_INTERVAL;

export const DAPPS_LIST_SYNC_INTERVAL = LONG_INTERVAL;

export const USER_ACTION_TIMEOUT = 30_000;

export const DEFAULT_WALLET_AUTOLOCK_TIME = LONG_INTERVAL;

export const COLLECTIBLES_DETAILS_SYNC_INTERVAL = LONG_INTERVAL;

export const NO_CATEGORY_ASSETS_METADATA_SYNC_INTERVAL = LONG_INTERVAL;

export const LIFI_SUPPORTED_CHAIN_IDS_INTERVAL = LONG_INTERVAL * 12;
