export const BLOCK_DURATION = 15_000;

export const ASSETS_SYNC_INTERVAL = 4 * BLOCK_DURATION;

const LONG_INTERVAL = 5 * 60_000;

export const RATES_SYNC_INTERVAL = LONG_INTERVAL;

export const NOTIFICATIONS_SYNC_INTERVAL = LONG_INTERVAL;

export const USER_ACTION_TIMEOUT = 30_000;

export const WALLET_AUTOLOCK_TIME = LONG_INTERVAL;

export const COLLECTIBLES_DETAILS_SYNC_INTERVAL = LONG_INTERVAL;
