export const EVERSTAKE_BAKER_ADDRESS = 'tz1aRoaRhSpRYvFdyvgWLL6TGyRoGF51wDjM';
export const HELP_UKRAINE_BAKER_ADDRESS = 'tz1bMFzs2aECPn4aCRmKQWHSLHF8ZnZbYcah';
export const TEMPLE_BAKER_ADDRESS = 'tz3N81sVKX29idiZMdT5JJZrTQyx5csT2Vhy';
