export const ROUTE3_CONTRACT = 'KT1Tuta6vbpHhZ15ixsYD3qJdhnpEAuogLQ9';
export const ROUTING_FEE_ADDRESS = 'tz1XYSt74vwVWgixEXdiS4C5t3UvuExRRTZR';

const ROUTING_FEE_PERCENT = 0.35;
export const ROUTING_FEE_RATIO = (100 - ROUTING_FEE_PERCENT) / 100;
