injectEnvironmentFiles:
  - .env?

approvedGitRepositories:
  - "https://github.com/madfish-solutions/jitsu-js.git"

enableScripts: true
nodeLinker: node-modules
npmMinimalAgeGate: "7d"
npmPreapprovedPackages:
  - "@temple-wallet/extension-ads"
  - "@specify-sh/publisher-sdk"
  - "@specify-sh/core"
npmRegistryServer: "https://registry.npmjs.org"
npmAuthToken: "${NPM_TOKEN:-}"
