name: "My composite action"
description: "Checks out the repository and does something"
runs:
  using: "composite"
  steps:
    - run: yarn install
      shell: bash

    - run: yarn ci
      shell: bash
