name: Code quality check
description: Installs dependencies and checks TS, linting, dead code

inputs:
  optional_modules:
    description: Install optional modules too
    required: true

runs:
  using: 'composite'
  steps:
    - run: yarn install
      if: inputs.optional_modules == 'true'
      shell: bash

    - run: yarn install --ignore-optional
      if: inputs.optional_modules != 'true'
      shell: bash

    - name: Audit dependencies
      run: yarn audit-deps
      shell: bash

    - name: Check TypeScript
      run: yarn ts
      shell: bash

    - name: Check E2E TypeScript
      run: yarn ts:e2e
      shell: bash

    - name: Find deadcode
      run: yarn find-deadcode
      shell: bash

    - name: Check ESLint
      run: yarn lint
      shell: bash

    - name: Perform unit tests
      run: yarn test:coverage
      shell: bash
