name: Code quality check
description: Installs dependencies and checks if ts, lint, unit tests
runs:
  using: 'composite'
  steps:
    - run: yarn install
      shell: bash

    - name: Check TypeScript
      run: yarn ts
      shell: bash

    - name: Find deadcode
      run: yarn find-deadcode
      shell: bash

    - name: Check ESLint
      run: yarn lint
      shell: bash

    - name: Run Unit tests
      run: yarn test:coverage
      shell: bash
