name: "Code quality check"
description: "Installs dependencies and checks if ts, lint, unit tests"
runs:
  using: "composite"
  steps:
    - run: yarn install
      shell: bash

    - run: yarn ts
      shell: bash

    - run: yarn lint
      shell: bash

    - run: yarn test:coverage
      shell: bash
