# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci
    match(type: "appstore", readonly: is_ci, api_key_path: "authkey.json")
    increment_build_number(build_number: ENV["BUILD_NUMBER"], xcodeproj: "TempleWallet.xcodeproj")
    build_app(workspace: "TempleWallet.xcworkspace", scheme: "TempleWallet")
    upload_to_testflight(api_key_path: "authkey.json", changelog: ENV["CHANGELOG"] || "No changelog provided")
  end
end
