export enum ChainSettingsSelectors {
  networkEnabledSwitch = 'Chain Settings/Network Enabled Switch',
  addRpcButton = 'Chain Settings/Add RPC Button',
  addExplorerButton = 'Chain Settings/Add Explorer Button',
  rpcEndpointItem = 'Chain Settings/RPC Endpoint Item',
  blockExplorerItem = 'Chain Settings/Block Explorer Item',
  activeRpcSwitch = 'Chain Settings/Active RPC Switch',
  activeExplorerSwitch = 'Chain Settings/Active Explorer Switch',
  activeRpcCheckbox = 'Chain Settings/Active RPC Checkbox',
  activeExplorerCheckbox = 'Chain Settings/Active Explorer Checkbox',
  nameInput = 'Chain Settings/Name Input',
  urlInput = 'Chain Settings/URL Input',
  deleteButton = 'Chain Settings/Delete Button',
  saveButton = 'Chain Settings/Save Button',
  confirmDeleteButton = 'Chain Settings/Confirm Delete Button',
  cancelDeleteButton = 'Chain Settings/Cancel Delete Button',
  pasteUrlButton = 'Chain Settings/Paste URL Button',
  removeNetworkButton = 'Chain Settings/Remove Network Button',
  cancelRemoveNetworkButton = 'Chain Settings/Cancel Remove Network Button',
  confirmRemoveNetworkButton = 'Chain Settings/Confirm Remove Network Button'
}
